name: 🚀 Feature Request
description: Suggest an idea for this project 💡
title: "CEO: "
labels: []
projects: ["InvictoProjects/6"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create this issue!
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the purpose or issue you're addressing. Be concise but descriptive.
      placeholder: Enter a concise summary of your request or problem.
      value: "Add a new feature for ..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
      value: "I propose the next solution ..."

